server:
  port: 8060
  # Problem Details without Stacktrace
  error:
    include-stacktrace: never

spring:
  application:
    name: order
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jackson:
    serialization:
      write-dates-as-timestamps: false
  # rabbitmq:
  #   listener:
  #     simple:
  #       default-requeue-rejected: false